### ISSUE TITLE
为什么ARAP的插值方法的动画很慢

### ISSUE THREAD

**Issue by facingmyfear** [lzero1115/ARAP_interpolation#1]
ARAP的插值方法的动画很慢而且演示不完全，是什么原因

**Comment by lzero1115** [comment]
Actually for now you need to keep pressing the start/pause button to run the interpolation process, which is really inconvenient. I will modify the code as soon as possible. But you can try the current code as I said above.

**Comment by lzero1115** [comment]
I will close this issue as the fix has been made.
